namespace ii.AscendancyLib.Model.Enum
{
    public enum PlanItem : byte
    {
        Factory = 0,
        Agriplot,
        Laboratory,
        Habitat,
        Metroplex,
        Colony_Base,
        Industrial_Megafacility,
        Artificial_Hydroponifer,
        Research_Campus,
        Logic_Factory,
        Engineering_Retreat,
        Surface_Cloaker,
        Hyperpower_Plant,
        Fertilization_Plant,
        Internet,
        Cloning_Plant,
        Observation_Installation,
        Tractor_Beam,
        Surface_Shield,
        Surface_Mega_Shield,
        Outpost,
        Transport_Tubes,
        Shipyard,
        Ship,
        Orbital_Docks,
        Orbital_Cloaker,
        Orbital_Shield,
        Orbital_Mega_Shield,
        Orbital_Missile_Base,
        Short_Range_Orbital_Whopper,
        Long_Range_Orbital_Whopper,
        Alien_Hospitality,
        Interstellar_Trucking,
        Endless_Party,
        Scientist_Takeover,
        Automation,
        Terraforming,
        Lush_Growth_Bomb,
        Xeno_Archeological_Dig,

        None = 255,
    }
}